### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by metapodcod** [Fraccs/youtooler-python#32]
Python 3.10.4
windows 10

```
[log] Successfully created the storage directory
Exception in thread Thread-1:
Traceback (most recent call last):
Exception in thread Thread-3:
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread Thread-5:
Exception in thread Thread-2:
Exception in thread Thread-4:
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
    self.run()
    self.run()
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\thread.py", line 33, in run
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\thread.py", line 33, in run
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\thread.py", line 33, in run
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\thread.py", line 33, in run
    tor = Tor(
    self.run()
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\thread.py", line 33, in run
    tor = Tor(
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 26, in __init__
    tor = Tor(
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 26, in __init__
    tor = Tor(
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 26, in __init__
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 26, in __init__
    self.hashed_password = self.__hash_password__()
    self.hashed_password = self.__hash_password__()
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 127, in __hash_password__
    tor = Tor(
    self.hashed_password = self.__hash_password__()
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 127, in __hash_password__
    self.hashed_password = self.__hash_password__()
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 127, in __hash_password__
    with Popen(COMMAND, stdout=PIPE, stderr=PIPE) as tor_hasher:
    with Popen(COMMAND, stdout=PIPE, stderr=PIPE) as tor_hasher:
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 127, in __hash_password__
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 26, in __init__
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    with Popen(COMMAND, stdout=PIPE, stderr=PIPE) as tor_hasher:
    with Popen(COMMAND, stdout=PIPE, stderr=PIPE) as tor_hasher:
    self.hashed_password = self.__hash_password__()
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
  File "C:\Users\metapodcod\Desktop\youtooler-python\src\youtooler\tor.py", line 127, in __hash_password__
    with Popen(COMMAND, stdout=PIPE, stderr=PIPE) as tor_hasher:
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    self._execute_child(args, executable, preexec_fn, close_fds,
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    self._execute_child(args, executable, preexec_fn, close_fds,
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  File "C:\Users\metapodcod\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
FileNotFoundError: [WinError 2] The system cannot find the file specified
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
FileNotFoundError: [WinError 2] The system cannot find the file specified
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Fraccs** [comment]
Hi @metapodcod, thanks for your report.

Currently youtooler only works on Linux but i'm planning to make it work on Windows in the near future.
